### ISSUE TITLE
Norton Antivirus doesn't like Chapter 9

### ISSUE THREAD

**Issue by kennetherland** [PacktPublishing/Hands-On-Machine-Learning-With-ML.NET#2]
My antivirus went nuts on the the TrainingData folder for chapter 9.  Are these files intentional?

**Comment by kennetherland** [comment]
Ahh.. (lightbulb!).. I just started reading your book and downloading the source was one of the first things I did.  I was not familiar with EICAR but I think I have heard the term thrown around by security analysts as "ee-car".  Wow.. thanks for the illuminated response.

**Comment by nithikpackt** [comment]
Thank you @jcapellman for the solution
